=== BitcoinErrorLog/slime/schemas/route.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Slime route v1",
  "type": "object",
  "properties": {
    "format": {
      "const": "slime-route/1"
    },
    "identity": {
      "$ref": "urn:slime:schema:common#/$defs/key"
    },
    "sequence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "issued_at": {
      "$ref": "urn:slime:schema:common#/$defs/time"
    },
    "homeservers": {
      "type": "array",
      "minItems": 1,
      "maxItems": 8,
      "uniqueItems": true,
      "items": {
        "$ref": "urn:slime:schema:common#/$defs/key"
      }
    },
    "failover": {
      "type": "object",
      "properties": {
        "key": {
          "$ref": "urn:slime:schema:common#/$defs/key"
        },
        "expires_at": {
          "$ref": "urn:slime:schema:common#/$defs/time"
        }
      },
      "required": [
        "key",
        "expires_at"
      ],
      "additionalProperties": false
    },
    "notice": {
      "type": "array",
      "maxItems": 8,
      "uniqueItems": true,
      "items": {
        "$ref": "urn:slime:schema:common#/$defs/key"
      }
    },
    "mirrors": {
      "type": "array",
      "maxItems": 8,
      "uniqueItems": true,
      "items": {
        "$ref": "urn:slime:schema:common#/$defs/key"
      }
    },
    "providers": {
      "type": "array",
      "maxItems": 8,
      "uniqueItems": true,
      "items": {
        "$ref": "urn:slime:schema:common#/$defs/key"
      }
    }
  },
  "required": [
    "format",
    "identity",
    "sequence",
    "issued_at",
    "homeservers"
  ],
  "additionalProperties": false
}

=== BitcoinErrorLog/slime/examples/headline/alice-route/route.json
{
  "failover": {
    "expires_at": "2027-03-20T12:00:00Z",
    "key": "y8s7w4d9d7fzih797b88ymx9qobggzczc9rc3ebdyhcfhsazko1y"
  },
  "format": "slime-route/1",
  "homeservers": [
    "pfju6i9x3ybssnjs6ibsy71tsznpwga7uh9ee6wzy5rfsnsh18oy",
    "q137yp465ytbgfj85k5gas64o99kaii5dwzgay8uogcfgt3bqiwo"
  ],
  "identity": "4pp1y4xkdpzquyp9wt7kxs395ihj93ioijt5nxq7xbr7khod4hcy",
  "issued_at": "2026-09-20T12:00:00Z",
  "notice": [
    "pczjo5k55rbz55ceohtso7mrmbc74senpsthsrs9i7js6socbbpy",
    "d7os3qkcpemhejh199u5nwi873mihoqjtxwy7b3k8m88sfb13m6y"
  ],
  "sequence": 1
}
