=== BitcoinErrorLog/slime/schemas/set.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Slime set v1",
  "type": "object",
  "properties": {
    "format": {
      "const": "slime-set/1"
    },
    "files": {
      "type": "array",
      "maxItems": 100000,
      "items": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1,
            "maxLength": 512,
            "pattern": "^[A-Za-z0-9_./-]+$"
          },
          "bytes": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "sha256": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          },
          "origin": {
            "type": "string",
            "format": "uri",
            "maxLength": 8192
          }
        },
        "required": [
          "path",
          "bytes",
          "sha256"
        ],
        "additionalProperties": false
      }
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "pattern": "Z$"
    },
    "previous": {
      "type": "string",
      "pattern": "^sha256:[0-9a-f]{64}$"
    }
  },
  "required": [
    "format",
    "files"
  ],
  "additionalProperties": false
}

=== BitcoinErrorLog/slime/examples/github-joined/set.json
{
  "created_at": "2026-09-23T13:00:00Z",
  "files": [
    {
      "bytes": 94,
      "path": "README.md",
      "sha256": "4cd99f597b1b9794a07e8dac6a4d0944e1d88672b1528065cda612e9e1f3a482"
    },
    {
      "bytes": 104,
      "origin": "pubky://dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y/pub/slime-example/tags/github-1.json",
      "path": "history/tag-1.json",
      "sha256": "4c559178fd99eb9ba50a779ea1fc35630611df103b0ad8e32d20a3085192d7a2"
    },
    {
      "bytes": 103,
      "origin": "pubky://dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y/pub/slime-example/tags/github-1.json",
      "path": "history/tag-2.json",
      "sha256": "38a11655ba48a6f7dfa56fbba06b0fd8e084c3ff33f6d54099d3e62b0492fc24"
    },
    {
      "bytes": 108,
      "origin": "pubky://dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y/pub/slime-example/tags/github-1.json",
      "path": "history/tag-3.json",
      "sha256": "228cbafbd3508bfb8a63841e4334e9bcc1a8df1e59bb5611166768a5c0443515"
    },
    {
      "bytes": 394,
      "path": "proofs/3a8f65d146ae26ec2aa72833bfe04b57936f8b3ff04d0d25083ff94dbaff9c26.json",
      "sha256": "3a8f65d146ae26ec2aa72833bfe04b57936f8b3ff04d0d25083ff94dbaff9c26"
    },
    {
      "bytes": 345,
      "path": "proofs/3a8f65d146ae26ec2aa72833bfe04b57936f8b3ff04d0d25083ff94dbaff9c26.sig.json",
      "sha256": "f8a2dee54a6d62e651bab02d8fb40ebaea2481ac053edf57ba96633ebde54ef6"
    },
    {
      "bytes": 313,
      "path": "proofs/a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51.json",
      "sha256": "a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51"
    },
    {
      "bytes": 345,
      "path": "proofs/a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51.sig.json",
      "sha256": "e137dd7c4f84ba7240d51d65ef8cf82f7947aae1d5a9e195040d2baed0a2c239"
    },
    {
      "bytes": 473,
      "path": "proofs/cf690f5036996e313139d55e3181ad1d9805f7b50c98f2864e7b772d4b9bec21.json",
      "sha256": "cf690f5036996e313139d55e3181ad1d9805f7b50c98f2864e7b772d4b9bec21"
    },
    {
      "bytes": 345,
      "path": "proofs/cf690f5036996e313139d55e3181ad1d9805f7b50c98f2864e7b772d4b9bec21.sig.json",
      "sha256": "48aa1c30bc3e2e73100799f9fc26f57f8dd78bc8f7b42c2148eb02ebe101076e"
    },
    {
      "bytes": 394,
      "path": "proofs/f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5.json",
      "sha256": "f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5"
    },
    {
      "bytes": 345,
      "path": "proofs/f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5.sig.json",
      "sha256": "dd7dce7ec3edfe6c9f437422ceb9c9a5601791b1352b74c0ba012d0604064790"
    }
  ],
  "format": "slime-set/1",
  "previous": "sha256:8e011c62b38bf9a2380ba19a6845a18d89af0f334036fd5e248d4abf51064be4"
}

=== BitcoinErrorLog/slime/examples/headline/bob-index-2/set.json
{
  "created_at": "2026-09-25T11:00:00Z",
  "files": [
    {
      "bytes": 211,
      "path": "README.md",
      "sha256": "edc5dbfb07a1f4deeef85a9f64136cede130614bfd60bcab46185c8e16c67a3d"
    },
    {
      "bytes": 2604,
      "path": "index.json",
      "sha256": "fd12f1be589758e5d93f683138072454f569b73ffaddb1f5c40bc344f94fe7d1"
    },
    {
      "bytes": 316,
      "path": "proofs/3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3.json",
      "sha256": "3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3"
    },
    {
      "bytes": 345,
      "path": "proofs/3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3.sig.json",
      "sha256": "22dfe0210a1beb50a9664b403aa9ce9e35fa45087f5eb6595f6228228d1a5802"
    },
    {
      "bytes": 304,
      "path": "proofs/58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd.json",
      "sha256": "58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd"
    },
    {
      "bytes": 345,
      "path": "proofs/58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd.sig.json",
      "sha256": "d90cc06004d48c6a6dd9da2e0cffa05a03c4a8e8e4a95bfe2c8778602af5e431"
    },
    {
      "bytes": 311,
      "path": "proofs/c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906.json",
      "sha256": "c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906"
    },
    {
      "bytes": 345,
      "path": "proofs/c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906.sig.json",
      "sha256": "37fd6da2ea4e92d21d063d0063869e6ad4e42412123b53ec4fde19abea6eac7b"
    },
    {
      "bytes": 176,
      "origin": "pubky://8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy/pub/slime-example/tags/shop-1.json",
      "path": "records/8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy/pub/slime-example/tags/shop-1.json",
      "sha256": "ea1461ba8b814b6c74c88a71de988c4a68aee4f35e66f0a3d73a3e9d915aebb9"
    },
    {
      "bytes": 176,
      "origin": "pubky://by8p8hf7i95w89niyfpkauy6j37kg9ehru5wrm9dfp1pg3pr7c5o/pub/slime-example/tags/print-2.json",
      "path": "records/by8p8hf7i95w89niyfpkauy6j37kg9ehru5wrm9dfp1pg3pr7c5o/pub/slime-example/tags/print-2.json",
      "sha256": "8221b438d4e800bc5490535c1418eec60106e5abd0d0109d3b61038d30a02fd2"
    },
    {
      "bytes": 108,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/blobs/dc0a6bcfa8b224dadda57c997ec68bf786c1d2a6d479c958b52c12b8c0b44135",
      "path": "records/kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/blobs/dc0a6bcfa8b224dadda57c997ec68bf786c1d2a6d479c958b52c12b8c0b44135",
      "sha256": "dc0a6bcfa8b224dadda57c997ec68bf786c1d2a6d479c958b52c12b8c0b44135"
    },
    {
      "bytes": 634,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/print-2.json",
      "path": "records/kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/print-2.json",
      "sha256": "f83c6058dec437d083a59df31009937129fece0f9b735c909ed64419a372d5a9"
    },
    {
      "bytes": 474,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/shirt-1.json",
      "path": "records/kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/shirt-1.json",
      "sha256": "99a2e249dcf6baf80b8deefe07a0851f54463b0bda5e13a0e09d5cb398d1e640"
    },
    {
      "bytes": 326,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/shop.json",
      "path": "records/kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/shop.json",
      "sha256": "d470c2bf78ebf40c4a58834e4282209f4d33eb1701cbfe4c482d7f6752b21c24"
    }
  ],
  "format": "slime-set/1",
  "previous": "sha256:499b2299c5ab09c5af41a4eed12cd09a8bef1415f01c8e81772c6c2ccb2b26b0"
}

=== BitcoinErrorLog/slime/examples/github-history/set.json
{
  "created_at": "2026-09-23T13:00:00Z",
  "files": [
    {
      "bytes": 145,
      "path": "README.md",
      "sha256": "206eba6f5a997fdf76c9c637c9e6230e16c75d3024c6b904a607e335ae32f7cc"
    },
    {
      "bytes": 104,
      "origin": "pubky://dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y/pub/slime-example/tags/github-1.json",
      "path": "history/tag-1.json",
      "sha256": "4c559178fd99eb9ba50a779ea1fc35630611df103b0ad8e32d20a3085192d7a2"
    },
    {
      "bytes": 103,
      "origin": "pubky://dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y/pub/slime-example/tags/github-1.json",
      "path": "history/tag-2.json",
      "sha256": "38a11655ba48a6f7dfa56fbba06b0fd8e084c3ff33f6d54099d3e62b0492fc24"
    },
    {
      "bytes": 335,
      "path": "proofs/36d2fac2b4d0c67da293f23bd0498fc9f0393c99b495d64752d03e07934004bd.json",
      "sha256": "36d2fac2b4d0c67da293f23bd0498fc9f0393c99b495d64752d03e07934004bd"
    },
    {
      "bytes": 345,
      "path": "proofs/36d2fac2b4d0c67da293f23bd0498fc9f0393c99b495d64752d03e07934004bd.sig.json",
      "sha256": "65423a03ae35207ced14c5e819038885d8acc4894eeb5f9caf28c9fb19ff9846"
    },
    {
      "bytes": 313,
      "path": "proofs/a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51.json",
      "sha256": "a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51"
    },
    {
      "bytes": 345,
      "path": "proofs/a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51.sig.json",
      "sha256": "e137dd7c4f84ba7240d51d65ef8cf82f7947aae1d5a9e195040d2baed0a2c239"
    },
    {
      "bytes": 394,
      "path": "proofs/f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5.json",
      "sha256": "f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5"
    },
    {
      "bytes": 345,
      "path": "proofs/f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5.sig.json",
      "sha256": "dd7dce7ec3edfe6c9f437422ceb9c9a5601791b1352b74c0ba012d0604064790"
    }
  ],
  "format": "slime-set/1",
  "previous": "sha256:0f1350920bfc42293d6f840cde0c115f9cebaeb738dacf34b94749d4c42b7a30"
}

=== BitcoinErrorLog/slime/examples/shops-withdrawn/set.json
{
  "created_at": "2026-09-23T13:00:00Z",
  "files": [
    {
      "bytes": 340,
      "path": "README.md",
      "sha256": "ec1714394b904eba9677e6bdd7103a2d7056b91e9d5c38e5e8b5851ab2f6dc0b"
    },
    {
      "bytes": 474,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/shirt-1.json",
      "path": "history/listing-before-withdrawal.json",
      "sha256": "99a2e249dcf6baf80b8deefe07a0851f54463b0bda5e13a0e09d5cb398d1e640"
    },
    {
      "bytes": 106,
      "path": "keys.txt",
      "sha256": "16c682eb19510a359caba3899748836f8a4926238b29f7b6273478a2a902e2e0"
    },
    {
      "bytes": 101,
      "path": "links.txt",
      "sha256": "424d6b873043b8f56f6b07ee8a749aa4a6ea7ad16f062e29f57cfd7a2dc8b597"
    },
    {
      "bytes": 316,
      "path": "proofs/3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3.json",
      "sha256": "3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3"
    },
    {
      "bytes": 345,
      "path": "proofs/3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3.sig.json",
      "sha256": "22dfe0210a1beb50a9664b403aa9ce9e35fa45087f5eb6595f6228228d1a5802"
    },
    {
      "bytes": 304,
      "path": "proofs/58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd.json",
      "sha256": "58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd"
    },
    {
      "bytes": 345,
      "path": "proofs/58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd.sig.json",
      "sha256": "d90cc06004d48c6a6dd9da2e0cffa05a03c4a8e8e4a95bfe2c8778602af5e431"
    },
    {
      "bytes": 397,
      "path": "proofs/5cd9754791a8c5518d39444d20695bec1c17b6168689e10440e6402fbd757aca.json",
      "sha256": "5cd9754791a8c5518d39444d20695bec1c17b6168689e10440e6402fbd757aca"
    },
    {
      "bytes": 345,
      "path": "proofs/5cd9754791a8c5518d39444d20695bec1c17b6168689e10440e6402fbd757aca.sig.json",
      "sha256": "fd40e3e3601f34d22e4ebc9b326a8644d4d528fbf5e132663c0243ff6f0740a1"
    },
    {
      "bytes": 311,
      "path": "proofs/c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906.json",
      "sha256": "c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906"
    },
    {
      "bytes": 345,
      "path": "proofs/c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906.sig.json",
      "sha256": "37fd6da2ea4e92d21d063d0063869e6ad4e42412123b53ec4fde19abea6eac7b"
    },
    {
      "bytes": 176,
      "origin": "pubky://8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy/pub/slime-example/tags/shop-1.json",
      "path": "records/8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy/pub/slime-example/tags/shop-1.json",
      "sha256": "ea1461ba8b814b6c74c88a71de988c4a68aee4f35e66f0a3d73a3e9d915aebb9"
    },
    {
      "bytes": 474,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/shirt-1.json",
      "path": "records/kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/listings/shirt-1.json",
      "sha256": "615b98b3c859f0a29ac85313907623d8b63178e2027aceaa078a5f0e65de4df1"
    },
    {
      "bytes": 326,
      "origin": "pubky://kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/shop.json",
      "path": "records/kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no/pub/slime-example/shop.json",
      "sha256": "d470c2bf78ebf40c4a58834e4282209f4d33eb1701cbfe4c482d7f6752b21c24"
    }
  ],
  "format": "slime-set/1",
  "previous": "sha256:ab9454f308f2ea05858dc7309ca6dd4788ce717c716a2dd0874354e008eab64d"
}
