=== BitcoinErrorLog/slime/schemas/signature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Slime signature v1",
  "type": "object",
  "properties": {
    "format": {
      "const": "slime-signature/1"
    },
    "purpose": {
      "enum": [
        "set",
        "record",
        "provider"
      ]
    },
    "algorithm": {
      "const": "Ed25519"
    },
    "signer": {
      "type": "string",
      "pattern": "^[ybndrfg8ejkmcpqxot1uwisza345h769]{52}$"
    },
    "digest": {
      "type": "string",
      "pattern": "^sha256:[0-9a-f]{64}$"
    },
    "signature": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{86}$"
    }
  },
  "required": [
    "format",
    "purpose",
    "algorithm",
    "signer",
    "digest",
    "signature"
  ],
  "additionalProperties": false
}

=== BitcoinErrorLog/slime/examples/github-signed/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:0f1350920bfc42293d6f840cde0c115f9cebaeb738dacf34b94749d4c42b7a30",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "DbbpQH9j0W-1lafCOkxE0iVexak-ej7LlVdK3i2QCQUqFNw5YLgoYtlXfLPIqZ4bzcghT3YHo7Sp9Ahm_1rLDg",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}

=== BitcoinErrorLog/slime/examples/headline/bob-slice-1/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:d14194fa8509f381e2a3301c0d039b55da57f422918d7e541286b57f3b3f2c9c",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "G00O7OYVhcZneXYgAGBbwI4Iz3fFuQu0JmludaZOKiUmiO3gkpUS95Rv0-MIcLx_0-L-ByJYX94u5z1AFRqnAQ",
  "signer": "xow6mmo7j5her6boj1er4mdskyhsrzewr81iqqpk3bogyuq9o1io"
}

=== BitcoinErrorLog/slime/examples/github-joined/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:16bc3c52d9476757938e11a725a6eff13bf11d2e8eb33c08b77300fb7188d158",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "C2Cqel3trNsGBrIsNfV_wQskdNbeN4ZaNd1TI7k_8FgBX9ZoraiNi0ouUa_y_fgvi4veCGA2i-6Zq-hqQpLyDQ",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}

=== BitcoinErrorLog/slime/examples/headline/bob-index-1/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:499b2299c5ab09c5af41a4eed12cd09a8bef1415f01c8e81772c6c2ccb2b26b0",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "t2ogOXep3C0wD-uwrns2XwZfACOLu8Zto99VbT4BWDmGXVT8D_VlocuWJVSJgIJf9cvrkpXac-3BvsFl9SbdDA",
  "signer": "xey9uh3brn1wrth34jruunmy5t739xew56hacergjprd9nfoc9yo"
}

=== BitcoinErrorLog/slime/examples/shops-public/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:ab9454f308f2ea05858dc7309ca6dd4788ce717c716a2dd0874354e008eab64d",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "w0TnBn1QOBUfL230txMakXcq9V_CY2RvxOcI5ZQ06o50oFfuR10XT6aFd-7Tgc6s2rZ0fnNw_mUqe9nojsiuBg",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}

=== BitcoinErrorLog/slime/examples/github-fork/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:8e011c62b38bf9a2380ba19a6845a18d89af0f334036fd5e248d4abf51064be4",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "clQDn3JJ1QMkc96AVvbAhYNuw09I3DvwuYrGPnOyZxUX_3ceWvBhQaMiDvDD5o3JOYmZ4c2Vz2_4fNU1Pi4UAQ",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}

=== BitcoinErrorLog/slime/examples/github-fork/proofs/3a8f65d146ae26ec2aa72833bfe04b57936f8b3ff04d0d25083ff94dbaff9c26.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:3a8f65d146ae26ec2aa72833bfe04b57936f8b3ff04d0d25083ff94dbaff9c26",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "gLD9IOiEHXy3IA_SfrSa7zsqHwqJdmjoawPimgwqTywci4UqXhLFop8bCc_dAilxzKo277CPd_Y07In-CLd0Aw",
  "signer": "dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y"
}

=== BitcoinErrorLog/slime/examples/github-joined/proofs/cf690f5036996e313139d55e3181ad1d9805f7b50c98f2864e7b772d4b9bec21.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:cf690f5036996e313139d55e3181ad1d9805f7b50c98f2864e7b772d4b9bec21",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "IAQuUmQeLCk9IwBm2t20mA-F_dqyMa383rfCErtw9iunrfqAWbwavckL7Rf8WcUYliNEhsUoyMNM2z71why-DA",
  "signer": "dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y"
}
