=== BitcoinErrorLog/slime/schemas/signature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Slime signature v1",
  "type": "object",
  "properties": {
    "format": {
      "const": "slime-signature/1"
    },
    "purpose": {
      "enum": [
        "set",
        "record",
        "provider"
      ]
    },
    "algorithm": {
      "const": "Ed25519"
    },
    "signer": {
      "type": "string",
      "pattern": "^[ybndrfg8ejkmcpqxot1uwisza345h769]{52}$"
    },
    "digest": {
      "type": "string",
      "pattern": "^sha256:[0-9a-f]{64}$"
    },
    "signature": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{86}$"
    }
  },
  "required": [
    "format",
    "purpose",
    "algorithm",
    "signer",
    "digest",
    "signature"
  ],
  "additionalProperties": false
}

=== BitcoinErrorLog/slime/examples/shops-withdrawn/proofs/5cd9754791a8c5518d39444d20695bec1c17b6168689e10440e6402fbd757aca.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:5cd9754791a8c5518d39444d20695bec1c17b6168689e10440e6402fbd757aca",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "tW9EEAfv0ESpkSt9CA-sypjzV64Gcel5Ihgkz8ES2zW2mvnYoOscOBF1nf3H7ngGZZJeY1LdfaY_78SLbHPTBA",
  "signer": "kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no"
}

=== BitcoinErrorLog/slime/examples/github-history/proofs/36d2fac2b4d0c67da293f23bd0498fc9f0393c99b495d64752d03e07934004bd.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:36d2fac2b4d0c67da293f23bd0498fc9f0393c99b495d64752d03e07934004bd",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "GMXrvc4B7fXETXnrxdNhuLgr3lAK2KUCdARlCyceLyXam20nQuvj_f5PS5uxK5gfpRbK_YS6GT59vMi3elYlAA",
  "signer": "dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y"
}

=== BitcoinErrorLog/slime/examples/headline/bob-index-2/proofs/c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:c756e288a9502bc82f01f6a4d8eb26812dce9ae5148dfa76991da7468e70f906",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "eV7i3d25pFW971JnHwi1O4Jwu02xHcZbqXEXQ1EL3l4wugkUmf_3ybkDa-hqn4XMryGBGBgcotZ9kYCAIN1GCQ",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}

=== BitcoinErrorLog/slime/examples/github-history/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:cfbf031f03347fa82d0428181c6216cf81bbdfa22c9247ecc6b9ae78e5e893a0",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "noTotPV4NP7Fu6eA3jVlzsctVM0N7moa9x6eVsk9Ewf_PpYNA0B4FsbWCStHjXMzDMHH3P073uCWTu2oZQ-aDA",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}

=== BitcoinErrorLog/slime/examples/github-history/proofs/f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:f9151b27f4c45a3ff208285676034610803ff584f21de6193c914d0f876ca2f5",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "xxy2-ycXMlmmr8MYkClKo6NGXpOXuizukFO2avzldjezuiY0o2MreJFsW7-3vZxvZ8CD6tTT6YEQqxs48YD_BA",
  "signer": "dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y"
}

=== BitcoinErrorLog/slime/examples/headline/bob-provider/provider.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:66d838dcfe4d12b69a2a20b77c7aa040950495d43e1b3bf590d83e389f3c957a",
  "format": "slime-signature/1",
  "purpose": "provider",
  "signature": "L9U1JmhEBZi4xinqaPL52wdxrE-53_hnyUwu9qeloDth8m3bBSuES2mIaclUCKehoGK1pwm26TGrO0WoqWS0Dg",
  "signer": "pczjo5k55rbz55ceohtso7mrmbc74senpsthsrs9i7js6socbbpy"
}

=== BitcoinErrorLog/slime/examples/shops-public/proofs/3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:3b7db4cb049f0d74c7220245e936e5db4b5c5cf0e76a4618488fdb5cf72e05a3",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "wQZkO3wcWgsXRDfDVu82SYJhnzBz1bkuZ6oAbBN0oVZxSLfrlr0YAinETojorKqOHBCizdJS1p1D_8FnoalNAg",
  "signer": "kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no"
}

=== BitcoinErrorLog/slime/examples/shops-withdrawn/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:88ad50f6ecea2d96a031d27c133f4da8534d853ce7e129371f4071f9da0659e4",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "LIFknLJjztz1Jiu6vsJlnoNiA5gAogefyRk3cjyqHoxHM_dHzX1duip4w3KxHtLU6_GznQ3JjmusWruKbLjDAw",
  "signer": "8nwd7x787d4xxy6r349npowdz136ibmmnpmyk1m8oxw6faa6oigy"
}
