=== BitcoinErrorLog/slime/schemas/signature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Slime signature v1",
  "type": "object",
  "properties": {
    "format": {
      "const": "slime-signature/1"
    },
    "purpose": {
      "enum": [
        "set",
        "record",
        "provider"
      ]
    },
    "algorithm": {
      "const": "Ed25519"
    },
    "signer": {
      "type": "string",
      "pattern": "^[ybndrfg8ejkmcpqxot1uwisza345h769]{52}$"
    },
    "digest": {
      "type": "string",
      "pattern": "^sha256:[0-9a-f]{64}$"
    },
    "signature": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{86}$"
    }
  },
  "required": [
    "format",
    "purpose",
    "algorithm",
    "signer",
    "digest",
    "signature"
  ],
  "additionalProperties": false
}

=== BitcoinErrorLog/slime/examples/headline/bob-slice-2/proofs/58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:58db0515e74b102d052c06e202fe34636c068e6dfc45352ef669f53c241a7cfd",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "0uVaOTom3D-FYSWdbOAJr_F-UQ5Wn7CkQg2WEKuT4XAL8WR5hIg7LMYpuZL7xHjE_rd0mwo72oiXbj0rsyHQAQ",
  "signer": "kq47ts1oghjief4acyjc7q8nuut5iodyw48atubb5d9h1gmoz1no"
}

=== BitcoinErrorLog/slime/examples/headline/bob-index-2/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:bbb7212e57db593c449b8a70dccecf76b8d23da8af90c868940872faf28de84d",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "Kl0XhzYGkfMlr5unbD2V3SypUKk9MQGijaieWQZ87RUuHnKzW2S7mCDnv-EWh-HIJeZotJiSxCvX-U6RRV5OCg",
  "signer": "xey9uh3brn1wrth34jruunmy5t739xew56hacergjprd9nfoc9yo"
}

=== BitcoinErrorLog/slime/examples/github-fork/proofs/a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:a8b944d1895667d8d840b940cf7a3dd27c9445768f0d832dc4c231668309cf51",
  "format": "slime-signature/1",
  "purpose": "record",
  "signature": "Eykm2UHuKggTNosTF9jcXaMVUwQ5mSW2j6Vo3F203Q-4Xg1KniNXz9j49gel7GJAfckfXx8v6IHKUcmrwTwaAw",
  "signer": "dbnm5egbtdsk7c5hhufrbpmdxge6h7of7c83qc7wygy1m7qhug6y"
}

=== BitcoinErrorLog/slime/examples/headline/bob-slice-2/set.sig.json
{
  "algorithm": "Ed25519",
  "digest": "sha256:8843b7f49579c1414e7316df55ca48b0a2ef5a91b3a2d2cdd269d621eedefe86",
  "format": "slime-signature/1",
  "purpose": "set",
  "signature": "BcZPKJy9j86z0Dc6yvgSe3wqNZfglMg9LkwBJUXdcvh06Gi8HLQZTNe0CHAfPJzzevODBl6GrcsVUlog0TSWAA",
  "signer": "xow6mmo7j5her6boj1er4mdskyhsrzewr81iqqpk3bogyuq9o1io"
}
